site_name: Portafolio Profesional
site_description: Perfil profesional minimalista
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: grey
nav:
  - Inicio: index.md
  - Experiencia: experiencia.md
  - Educación: educacion.md
  - Deportes: deportes.md